---
title: "Voter Turnout Lasso"
author: "Anvita Kallam"
date: "2024-07-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, fig.width=8, fig.height=4)
options(scipen = 999, digits = 3)  # controls base R output

# Package setup
if(!require("pacman")) install.packages("pacman")

pacman::p_load(car, tidyverse, dplyr, ggplot2, data.table, lubridate, 
               glmnet, kableExtra, stargazer, scales, viridis, knitr, readr, usmap)

```

## Model with All Factors

See what are the factors and significance

```{r}

data1 <- read.csv('data/TurnoutFinal.csv')

summary(data1)


```

```{r cars}

fit1 <- lm(Turnout ~ Year + State + Gov_Party + HDI + Num_Violent_Crimes + Med_Inc + Unemployment_Rate + gini_coef + swing, data = data1)

Anova(fit1)

plot(fit1)

```

## Lasso

Finalize which factors impact it


```{r, warning=FALSE}

library(caret)
library(glmnet)

X <- data1
y <- data1$Turnout


X <- X[, colnames(X) != "Turnout"]


set.seed(20)

trainIndex <- createDataPartition(y, p = .75, list = FALSE, times = 1)
X_train_test <- X[trainIndex, ]
X_val <- X[-trainIndex, ]
y_train_test <- y[trainIndex]
y_val <- y[-trainIndex]


set.seed(20)
trainIndex2 <- createDataPartition(y_train_test, p = .5, list = FALSE, times = 1)
X_train <- X_train_test[trainIndex2, ]
X_test <- X_train_test[-trainIndex2, ]
y_train <- y_train_test[trainIndex2]
y_test <- y_train_test[-trainIndex2]


X_train <- as.matrix(X_train)
X_val <- as.matrix(X_val)

```

```{r, warning=FALSE}
set.seed(20)
lasso_model_final <- cv.glmnet(X_train, y_train, alpha = 1)


best_lambda <- lasso_model_final$lambda.min


predictions <- predict(lasso_model_final, s = 'lambda.min', newx = X_val)


coef.min <- coef(lasso_model_final, s = best_lambda)
non_zero_coefs <- coef.min[which(coef.min != 0),]


rmse <- sqrt(mean((predictions - y_val)^2))
cat("Root Mean Squared Error (RMSE):", rmse, "\n")


rss <- sum((predictions - y_val)^2)
cat("Residual Sum of Squares (RSS):", rss, "\n")



```


```{r}

non_zero_coefs
plot(lasso_model_final)

best_lambda

```

```{r, warning=FALSE}

set.seed(20)
train_index <- sample(1:nrow(data1), 0.85*nrow(data1))
train_data <- data1[train_index,]
test_data <- data1[-train_index,]

y_test <- test_data$Turnout

relaxed_model <- lm(Turnout ~ Year + HDI + Num_Violent_Crimes + gini_coef, data = train_data)

Anova(relaxed_model)

plot(relaxed_model)

predictions2 <- predict(relaxed_model, newx = test_data)

mse <- sqrt(mean((predictions2 - y_test)^2))
cat("Root Mean Squared Error (RMSE):", mse, "\n")

rss <- sum((predictions2 - y_test)^2)
cat("Residual Sum of Squares (RSS):", rss, "\n")

```


```{r}

summary(relaxed_model)

```