---
title: "Voter Turnout Heatmaps"
author: "Anvita Kallam"
date: "2024-07-24"
output: html_document
---

```{r Setup, include=FALSE, results='hide', warning=FALSE}
knitr::opts_chunk$set(echo = T, fig.width=8, fig.height=4)
options(scipen = 999, digits = 3)  # controls base R output

# Package setup
if(!require("pacman")) install.packages("pacman")

pacman::p_load(car, tidyverse, dplyr, ggplot2, data.table, lubridate, 
               glmnet, kableExtra, stargazer, scales, viridis, knitr, readr, usmap)

```

## Heatmaps of Voter Turnout by Year

Let's examine the data by exploring how the spread of voter turnout percentages has changed over the years, from 2000 to 2020 each presidential election.


```{r warning=FALSE}

# library(usmap)
# library(ggplot2)
# library(dplyr)
# library(viridis)
# 
# data <- read.csv('data/voterTurnout_Heatmap.csv')
# 
# data <- data %>%
#   rename(state = states)
# 
# 
# create_heatmap <- function(year, data) {
#   year_data <- filter(data, Year == year)
#   
# 
#   # Plot the heatmap
#   plot_usmap(regions = "state", data = year_data, values = "Turnout") +
#     scale_fill_viridis(option = "magma", direction = -1, name = "Voter Turnout Rate") +
#     theme(legend.position = "right") +
#     ggtitle(paste("Voter Turnout Rate by State -", year))
# }
# 
# years <- unique(data$Year)
# 
# for (year in years) {
#   print(create_heatmap(year, data))
#   
#   
# }
```


```{r}

library(usmap)
library(ggplot2)
library(dplyr)
library(viridis)

# Load the data
data <- read.csv('data/voterTurnout_Heatmap.csv')

# Rename the state column
data <- data %>%
  rename(state = states)

# Calculate the global min and max for Turnout
global_min_turnout <- min(data$Turnout, na.rm = TRUE)
global_max_turnout <- max(data$Turnout, na.rm = TRUE)

# Function to create heatmap for a given year
create_heatmap <- function(year, data, global_min, global_max) {
  year_data <- filter(data, Year == year)
  
  # Plot the heatmap
  plot_usmap(regions = "state", data = year_data, values = "Turnout") +
    scale_fill_viridis(option = "magma", direction = -1, name = "Voter Turnout Rate",
                       limits = c(global_min, global_max)) +
    theme(legend.position = "right") +
    ggtitle(paste("Voter Turnout Rate by State -", year))
}

# Get unique years from the data
years <- unique(data$Year)

# Generate and print heatmap for each year
for (year in years) {
  print(create_heatmap(year, data, global_min_turnout, global_max_turnout))
}


```

```{r}

max(data$Turnout, na.rm = TRUE)

```