---
title: "Voter Turnout Arima"
author: "Anvita Kallam"
date: "2024-07-29"
output: html_document
---

```{r setup, include=FALSE}
library(forecast)
library(ggplot2)
library(zoo)
library(caret)

knitr::opts_chunk$set(echo = T, fig.width=8, fig.height=4)
options(scipen = 999, digits = 3)  # controls base R output

# Package setup
if(!require("pacman")) install.packages("pacman")

pacman::p_load(car, tidyverse, dplyr, ggplot2, data.table, lubridate, 
               glmnet, kableExtra, stargazer, scales, viridis, knitr, readr, usmap)


data <- read.csv('data/TurnoutFinal.csv')


```

## Arima Model


```{r}

create_zoo_per_state <- function(State) {
  zoo(State$Turnout, order.by = State$Year)
}

# Split the data by state and create zoo time series objects
state_zoo <- lapply(split(data, data$State), create_zoo_per_state)

state_zoo


```


```{r}

library(dplyr)
library(tidyr)
library(forecast)


head(data)

state_data <- split(data, data$State)

prepare_time_series <- function(df) {
  df <- df %>% arrange(Year)
  ts_data <- ts(df$Turnout, start = min(df$Year), frequency = 1)
  return(ts_data)
}

state_ts <- lapply(state_data, prepare_time_series)


state_ts_stationary <- lapply(state_ts, function(ts) {
  ndiffs(ts)
})


state_ts_diff <- mapply(function(ts, d) {
  if (d > 0) {
    diff(ts, differences = d)
  } else {
    ts
  }
}, state_ts, state_ts_stationary, SIMPLIFY = FALSE)


library(zoo)


state_zoo <- lapply(state_ts_diff, function(ts) {
  as.zoo(ts)
})

state_zoo

```


```{r}

# plot_list <- lapply(names(state_zoo), function(state) {
#   autoplot(state_zoo[[state]]) +
#     ggtitle(paste("Voter Turnout Over Years - State", state)) +
#     xlab("Year") +
#     ylab("Turnout (%)")
# })
# 
# # Print plots
# for (p in plot_list) print(p)

```

```{r}

# plot_acf_pacf <- function(state_data, state_name) {
#   par(mfrow = c(1, 2))
#   acf(state_data, main = paste("ACF of Training Data - State", state_name))
#   pacf(state_data, main = paste("PACF of Training Data - State", state_name))
#   par(mfrow = c(1, 1))
# }
# 
# for (state in names(state_zoo)) {
#   train <- window(state_zoo[[state]], end = 2016)
#   plot_acf_pacf(train, state)
# }

```


```{r, echo=FALSE, warning=FALSE}

library(zoo)
library(ggplot2)
library(forecast)


create_zoo_per_state <- function(State) {
  zoo(State$Turnout, order.by = State$Year)
}

data <- read.csv("data/TurnoutFinal.csv")
state_zoo <- lapply(split(data, data$State), create_zoo_per_state)

# Function to fit ARIMA model and make predictions for each state
fit_arima_predict <- function(state_data, state_name) {
  state_data <- na.approx(state_data)
  
  # Split data into training and test sets
  train <- window(state_data, end = 2016)
  test <- window(state_data, start = 2020)
  
  # Fit the ARIMA model using specific (p,d,q) values
  model <- arima(train, order = c(1, 1, 0))

  forecasted <- predict(model, n.ahead = length(test))
  forecasted_values <- zoo(forecasted$pred, order.by = time(test))

  train_df <- fortify.zoo(train)
  test_df <- fortify.zoo(test)
  forecasted_df <- fortify.zoo(forecasted_values)
  
  
  # Plot the forecast
  plot_title <- paste("ARIMA Model Forecast for State", state_name)
  p <- ggplot() +
    geom_line(data = train_df, aes(Index, train_df[, 2]), color = "#561976") +
    geom_line(data = test_df, aes(Index, test_df[, 2]), color = "#b23579", linetype = "dashed") +
    geom_line(data = forecasted_df, aes(Index, forecasted_df[, 2]), color = "#f27062") +
    ggtitle(plot_title) +
    xlab("Year") +
    ylab("Turnout (%)")

  print(p)

  mae <- mean(abs(forecasted$pred - coredata(test)))
  rmse <- sqrt(mean((forecasted$pred - coredata(test))^2))
  rss <- sum((forecasted$pred - coredata(test))^2)
  cat(paste("State:", state_name, "\n"))
  cat(paste("Mean Absolute Error:", round(mae, 2), "\n"))
  cat(paste("Root Mean Squared Error:", round(rmse, 2), "\n", "\n"))
  
  return(list(model = model, forecasted = forecasted, mae = mae, rmse = rmse, rss = rss))
}


results <- lapply(names(state_zoo), function(State) {
  fit_arima_predict(state_zoo[[State]], State)
})


```

```{r}

library(ggplot2)

state_names <- names(state_zoo)
rmse_values <- sapply(results, function(result) result$rmse)

rmse_df <- data.frame(State = state_names, RMSE = rmse_values)
fitplot <- lm(rmse_values ~ state_names, rmse_df)

average_rmse <- mean(rmse_values)

ggplot(rmse_df, aes(x = State, y = RMSE, color = RMSE)) +
  geom_point(size = 2) +
  scale_color_viridis_c(option = "magma", direction = -1) +
  geom_hline(yintercept = average_rmse, color = "black", linetype = "dotted") +
  labs(title = "ARIMA Model: Root Mean Squared Error (RMSE) for Each State",
       x = "State",
       y = "RMSE") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

mean(rmse_values)

rss_values <- sapply(results, function(result) result$rss)

mean(rss_values)

```


```{r}

library(zoo)
library(ggplot2)
library(forecast)

# Function to create zoo object per state
create_zoo_per_state <- function(State) {
  zoo(State$Turnout, order.by = State$Year)
}

data <- read.csv("data/TurnoutFinal.csv")
state_zoo <- lapply(split(data, data$State), create_zoo_per_state)

# Function to fit ARIMA model and make predictions for each state
fit_arima_predict <- function(state_data, state_name) {
  state_data <- na.approx(state_data)
  
  # Split data into training and test sets
  train <- window(state_data, end = 2016)
  test <- window(state_data, start = 2016)
  
  # Fit the ARIMA model using specific (p,d,q) values
  model <- arima(train, order = c(1, 1, 0))

  # Predict until 2024
  forecasted <- predict(model, n.ahead = length(test) + 2) # length(test) + 2 to cover up to 2024
  forecasted_values <- zoo(forecasted$pred, order.by = seq(start(test), by = 4, length.out = length(test) + 2))
  
  train_df <- fortify.zoo(train)
  test_df <- fortify.zoo(test)
  forecasted_df <- fortify.zoo(forecasted_values)
  
  # Plot the forecast
  plot_title <- paste("ARIMA Model Forecast for State", state_name)
  p <- ggplot() +
    geom_line(data = train_df, aes(Index, train_df[, 2]), color = "blue") +
    geom_line(data = test_df, aes(Index, test_df[, 2]), color = "black", linetype = "dashed") +
    geom_line(data = forecasted_df, aes(Index, forecasted_df[, 2]), color = "red") +
    ggtitle(plot_title) +
    xlab("Year") +
    ylab("Turnout (%)")
  
  print(p)

  mae <- mean(abs(forecasted$pred[1:length(test)] - coredata(test)))
  rmse <- sqrt(mean((forecasted$pred[1:length(test)] - coredata(test))^2))
  cat(paste("State:", state_name, "\n"))
  cat(paste("Mean Absolute Error:", round(mae, 2), "\n"))
  cat(paste("Root Mean Squared Error:", round(rmse, 2), "\n", "\n"))
  
  return(list(model = model, forecasted = forecasted_values, mae = mae, rmse = rmse))
}

results <- lapply(names(state_zoo), function(State) {
  fit_arima_predict(state_zoo[[State]], State)
})

# Extract the forecasted values for 2024 and save them to a CSV
forecast_2024 <- data.frame(
  State = names(state_zoo),
  Turnout_2024 = sapply(results, function(res) {
    tail(res$forecasted, 1)
  })
)




```

```{r}

forecast_2024
write.csv(forecast_2024, "data/forecasted_turnout_2024.csv", row.names = FALSE)

```


```{r}

library(ggplot2)
library(usmap)
library(viridis)

predict_data <- read.csv('data/forecasted_turnout_2024.csv')

predict_data <- predict_data %>%
  rename(state = State)

# Ensure that the state abbreviations in the data are in uppercase to match with usmap data
predict_data$state <- toupper(predict_data$state)

# Plot the heatmap
plot_usmap(regions = "state", data = predict_data, values = "Turnout_2024") +
    scale_fill_viridis(option = "magma", direction = -1, name = "Predicted Turnout", 
      limits = c(38.3, 74.8)) +
    theme(legend.position = "right") +
    ggtitle("Voter Turnout Rate by State 2024")

```


```{r}

turn <- predict_data$Turnout_2024

mean(turn)

```